### ISSUE TITLE
Dragonfire Adept cannot select feats that require Breath weapon special ability

### ISSUE THREAD

**Issue by Ed-Zero** [BahamutDragon/pcgen#1049]
I noticed I was not able to select any feats that require a Breath Weapon special ability as a 1st level Dragonfire Adept, when I should be able to select it, as I do have a breath weapon and qualify for everything else.

The feats I've found so far are:
Entangling Exhalation
Exhaled Barrier
Exhaled Immunity
Extra Exhalation

![Feat not selectable](https://user-images.githubusercontent.com/36054876/126268812-354b8916-1220-4a2d-816f-3dba2ba79333.png)
![Breath Weapon](https://user-images.githubusercontent.com/36054876/126268814-694efab8-428c-4edb-9661-0bfad6d06d8c.png)

**Comment by FerretDave** [comment]
Ironically, I've found almost the reverse - so many 'monster' type feats are available to choose when they shouldn't be (due to pre-reqs of needing tentacles, or flight, or a tail attack etc!) - keep meaning to go through and add PRE's on those and add some options to add Tentacle/Flight/Tail etc abilities to select to enable them - just to cut the lists down an sanitise them a bit.

**Comment by BahamutDragon** [comment]
Should be fixed for Master (6.09.x)
