### ISSUE TITLE
5e edit possible number of attuned items?

### ISSUE THREAD

**Issue by uncreative54** [BahamutDragon/pcgen#1162]
I have a GM who is running magic items like previous versions of DnD, where the only limit on number of magic items is body slots.

I'm looking through code and it seems like dmg_abilitycategories is where I would change maximum number of attuned items a character can have, but I'm not sure exactly how to change it.

Could y'all just really quickly tell me where and what to type in to get more attunement slots?

Thank you!!!

**Comment by BahamutDragon** [comment]
More attunement slots? 

Change the value of this VAR:   Attuned_Item_Max from 3 to however high you want it. The var is found in the dmg_abilities.

The value is set to: 

BONUS:VAR|Attuned_Item_Max|2|TYPE=Base

If you wanted 5 items, then change the value to 

BONUS:VAR|Attuned_Item_Max|4|TYPE=Base

And if you want to understand, the formula is this:

PREVARLTEQ:Attuned_Item_Count,Attuned_Item_Max

If I had realized this value was going to be altered by others I'd have made it LT instead of LTEQ. Then the max value would reflect the correct value. I might as well change that so it is easy to follow. Disregard the above value and put the value you want.

**Comment by BahamutDragon** [comment]
And done. Current value is set to 3, change it to whatever you want.

BONUS:VAR|Attuned_Item_Max|3|TYPE=Base
