### ISSUE TITLE
Gestalt?

### ISSUE THREAD

**Issue by ralstad** [BahamutDragon/pcgen#1168]
Hello,

I am trying to write up a gestalt character but the Gestalt is not allowed when I choose the classes.
How can I make this work?

**Comment by BahamutDragon** [comment]
Hi mate!

Step 1: New Character
Step 2: Decide whether to use a Simple Gestalt (You use the exact same two classes), or Complex (You mix them up)

Simple uses the Gestalt Class found in the classes, while the complex you just add the classes multiple time in the MISC section. 

![image](https://github.com/BahamutDragon/pcgen/assets/4307487/2216e4a4-6a12-44ef-995e-c9fe5c9c8311)

If you have a spellcaster, I recommend adding that class specifically and level them normally, and then the non-caster gestalt, uses the abilities grantor as seen in this example:
![image](https://github.com/BahamutDragon/pcgen/assets/4307487/291b0afe-b37f-4f07-b3e0-379212fda92e)

Do note, the classes will not be reflected on the sheet properly - this is a cleric 3/monk 3:
![image](https://github.com/BahamutDragon/pcgen/assets/4307487/308f26bb-faf7-477d-b2c7-3050f544b353)

But the actually abilities will be displayed properly in the class features section. This is a very experimental feature, which means the values might not be correct. Use at your own discretion.

This system is not going to work well for two spell casters. Just be warned. If you need that support, then be very precise on the two classes you need and I will look at it but no promises since the program is not meant to be circumvented in this manner.

**Comment by BahamutDragon** [comment]
I've fixed the code, in theory the caster classes should operate correctly. However, you need to save and reopen after you add the initial caster class before the spells will populate.

**Comment by BahamutDragon** [comment]
While improved, there may be issues that crop up. Let me know if you encounter anything. Use the Gestalt class to have the level based benefits (skills and HD).
