### ISSUE TITLE
3.5e - Unable to add language after character creation

### ISSUE THREAD

**Issue by IluvatarTheReal** [BahamutDragon/pcgen#1219]
So I made a character and was able to add everything correctly! That worked great, upon reaching lvl 3, I wanted to add draconic language to my character but the dialog to add language simply doesn't work.

I tried the Add bonus language and the Add bonus via skill button, but neither works, they open up the dialog fine, but it never lets me add the language, its like the buttons are doing nothing.

**Comment by BahamutDragon** [comment]
What version of PCGen are you using? Can you attach the pcg file of the character that is not working?

**Comment by IluvatarTheReal** [comment]
Here is the zipped pcg file
[Gloin.zip](https://github.com/BahamutDragon/pcgen/files/14502597/Gloin.zip)

The version I have is 6.08.00 RC10, Release date 2023-02-04

**Comment by BahamutDragon** [comment]
Preferences -> House Rule -> Allow selection of Bonus Languages after 1st level

Otherwise, per the rules, you cannot select bonus languages after 1st level. Nothing for me to address:
![image](https://github.com/BahamutDragon/pcgen/assets/4307487/006db557-60d5-4edc-8421-500f0bc51b88)

![image](https://github.com/BahamutDragon/pcgen/assets/4307487/e352d058-75bf-4b7c-94e1-36dd77f4025e)

**Comment by IluvatarTheReal** [comment]
Is there a way to have access to -all- languages in that list? The same list being opened when you do add language via skill points? If not we'll just write down the language on the character sheet manually, but I was hoping I could add draconic to this character's language list.

**Comment by BahamutDragon** [comment]
Yes, you can opt to use the GM Award system and grant the character any language you want. Feat & Abilities > Misc (GM Awards) - Select Add Language. You should have a list of every spoken language much like a human.
