### ISSUE TITLE
5e - Clerics can only use cantrips

### ISSUE THREAD

**Issue by zephyyrr** [BahamutDragon/pcgen#199]
When I create a new cleric in 5e, no level 1 spells is listed as known.
If I attempt to add spells to my known list, I get the message:
"You can only learn 0 spells for level 1 and there are no higher-level slots available".

The table of known spells does state that I know 0 spells, but this must be wrong, since the basic rules allows me to cast level 1 spells.

I'm using 6.04.01 on windows. Latest version on appropriate branch.

**Comment by BahamutDragon** [comment]
Mate, there seems to be a bit more going on under the hood. For the classes that have no known cap, MEMORIZE:NO is the issue, removing that restores the spells to working order. For specific classes that use KNOWN, I think there is legacy java code requiring a minimum casting tied stat to be 10+ Spell Level. In order to get all classes working without the undue stat cap or otherwise, I will remove all the memorize tags. Those with caps will have to review the characters for accuracy till the issue is corrected. 

I have a belief that this issue, and others of its ilk will be removed when the old jep code is replaced by the new parser. Thanks for the report.
