### ISSUE TITLE
5e - Rogue lvl 3 - Arcane trickster

### ISSUE THREAD

**Issue by vehrka** [BahamutDragon/pcgen#207]
Hi,

I'm creating a lvl 3 Rogue with Arcane trickster as an Archetype and I've seen that it lacks of Cantrips and the Spell progression is wrong.

PCGen: 6.04.01
Repo last commit:  2bcd3ca32d

Thanks in advance

**Comment by vehrka** [comment]
Hi,

Also tryed to create a Wizard and the Spell progression is also wrong :(

Bests,

**Comment by BahamutDragon** [comment]
Are you using the "CAST" entry, or are you referencing the Spell Slots on the character sheet to get the progression?

Made a 6th level wizard, 1st = 4, 2nd = 3, 3rd = 3, 4th = 0, 5th = 0, 6th = 0, 7th = 0, 8th = 0, 9th = 0 
Chart - 4, 3, 3 for 6th level wizard. Appears to match to me. Example of the issue would be helpful in these situations mate. 

Deliberate design decision on to handle multi-classing in an easy manner and not use cast which would misrepresent the correct slots. CAST will only show if a given level is accessible. If cast was used, then all the classes would show the exact same number for CAST, and would not give a proper indicator when the class could cast. I am open to alternative solutions. This was a stop gap measure until a proper OS design could be implemented.


Cantrips were set up correctly for the main classes. Adding it to the secondary casting should not be too difficult.

**Comment by BahamutDragon** [comment]
Cantrip implemented for Arcane Trickster and Eldritch Knight.

Will need some example to verify the wizard progression is incorrect. Variables for the table appear to be implemented correctly.

**Comment by vehrka** [comment]
Hi,

sorry, I really thought I had attached the rogue's PC sheet file :(

I wasn't trying to create a multiclass PC there are two separate PC files but both show the wrong progression.

Both places, the CAST and the Character Sheet show the same info:

Rogue lvl 3 Arcane Trickster : Know 0:0/1:3 Per Day 0:0/1:1
Wizard lvl 1 : Known 0:3/1:0 Per Day 0:1/1:1
Wizard lvl 2 : Known 0:3/1:0 Per Day 0:1/1:1
Wizard lvl 3 : Known 0:3/1:0/2:0 Per Day 0:1/1:1/2:1

Please find attached referred files.

Thank you very much.

[Wizard_l3.pcg | uploaded via ZenHub](https://files.zenhub.io/5552f8a18fd825ae6d3e4f52)

[Rogue_l3.pcg | uploaded via ZenHub](https://files.zenhub.io/5552f8a18fd825ae6d3e4f4f)

[Wizard_l1.pcg | uploaded via ZenHub](https://files.zenhub.io/5552f8a18fd825ae6d3e4f50)

[Wizard_l2.pcg | uploaded via ZenHub](https://files.zenhub.io/5552f8a18fd825ae6d3e4f51)

**Comment by vehrka** [comment]
Hi,

after pulling to 3d2487bc1f the Rogue with Arcane Trickster can choose the Cantrips correctly but the Spell progression show CAST 1 for the 1st Level Slot.

Starting to think that I'm doing something wrong :(

[Rogue_l3_3d2487bc1f.pcg | uploaded via ZenHub](https://files.zenhub.io/5552fb4d8fd825ae6d3e4f58)

**Comment by BahamutDragon** [comment]
No mate, it was a design decision made on my part when factoring in the big picture which encompasses the multi-class angle.

The pcgen program has two pools for lack of a better term to work with. CAST pool, and KNOWN pool. CAST is usually the one to say how many slots you have available. In this instance, 1 is "Can cast this level" instead of "How many slots". Cast is translated to the Per Day on the PDF, which is why you think the progression is wrong.

The reason for this is simple. Single class progression is easy, you can make a CAST entry. The Slots match up to Level for the class. When you multiclass, you have a new "pool" split from cast. Able to cast this level and Slots available for level x. Worse, slots becomes a Shared pool for all the classes, not a per class pool, like earlier editions. Wizard 4, able to cast 2nd level spells; Cleric 2, able to cast 1st level spells. You would have a spell slot for a level 3 spell, but Cleric cannot cast a 3rd level spell, and neither can a Wizard. Yet, you would see a Per Day entry for both cleric and wizard on a level 3 header. Would you agree that is confusing?

It would be nice, when I have some time to invest, to alter the spell section for the classes. The Per Day entry should be changed to  "Can Cast this level" or "Cannot Cast this level", and put a header above that lists the Spell Slots available for all classes. 

To help, look on page 2 of the character sheet, find the Special Quality named "Spellcaster Spell Slots", that gives the correct number of slots available to any character. This was designed to work with all spellcasting classes.

**Comment by vehrka** [comment]
Hello,

OK, I see there are several implementation issues, hope  I can help somehow to improve your work, at least as a playtester.

It's true that in the second page of the Character Sheet the Spell Progression is OK, but as it is implemented right now, with the KNOW set to 0, I cannot add new spells to the character. 

When trying to add spells from the Spells tab I keep getting a warning message «You can only learn 0 spells for level X and there are no higher-level slots available».

I suppose that is a limitation set by the KNOW pool.

I consider it a «minor» issue because we use other resources for the spells description, but probably most users will find it annoying.

Thank you very much for the feedback.

**Comment by BahamutDragon** [comment]
>"When trying to add spells from the Spells tab I keep getting a warning message «You can only learn 0 spells for level X and there are no higher-level slots available»."

That is not intended to be annoying. KNOWN is set up to limit the number of spells the character has available to reliably reflect the rules and should only affect the classes with a limitation on spells available.

If this is a Wizard character, then we have an issue, since the Wizard can add spells to the spell book without limitation. I will recheck the code on my end.

**Comment by BahamutDragon** [comment]
Tested and pushed in a working fix to the ADD issue. If the class uses KNOWN as a limitation, the spells allowed are added up to your known limit by using MEMORIZE:NO on the class line. Non-known classes, such as wizard and cleric, use MEMORIZE:YES to allow unlimited selections. That should fix all your active concerns from this thread. Best,
