### ISSUE TITLE
Support FFG Star Wars Age of Rebelion and Force and Destiny

### ISSUE THREAD

**Issue by psychomantys** [BahamutDragon/pcgen#229]
Any chance to support this books?

The Edge of the Empire is available...

**Comment by BahamutDragon** [comment]
Mate,

I can make the data for it. The harder part is a proper character sheet. 

Edge of the Empire was an exercise to see what would be possible in pcgen. There are a few interesting mechanics that challenged pcgen, much like the Mutants and Masterminds. You would be the first to ask for anything related to it though. Do you have a specific era book you needed or is this just a wish list?

**Comment by psychomantys** [comment]
This is a wish list, but i can create the data for it if is possible create for PCGen.... 
I don't know about how to create game modes, but I can create the data books.

The question is, for the actual implementation of game mode of Star Wars, is possible use PCGen to make characters for Star Wars?

I try, but somethings dont look good... Like class and level, AC references or Encumbrance...

**Comment by BahamutDragon** [comment]
Mate,

I have a quasi working set for the Edge of the Empire rules. Quasi is due to the fact the numbers for stat creation do not work out quite right yet. Most of the other rulebooks re-use information from each book. The data can be reused for that.

PCGen should be able to support the system. The only issue I have encountered is the old jep system has issues processing all the numbers. I have been waiting for the feature that replaces the existing jep formula parser system. Good read, has powerful capability, and would handle most of the system mechanics easily. 

Starwars should not have any levels, classes or other references. All of that is reminders for the d20 hard code support. The summary tab with the d20 references can be removed or replaced. Same as the character sheets. 

I would say PCGen can support the system. It will not be quite as pretty until the pcgen team irons out the d20 references in the main engine. I understand they have plans to do that, just at the pace of the volunteers. 

I have a Gamemode for the system. All the books can use the same gamemode.
Data needs to be set up correctly, which can then be referenced to populate a character sheet. The hard part is adapting a character sheet that matches the star wars sheet.

**Comment by BahamutDragon** [comment]
Did you need anything on this mate?

**Comment by BahamutDragon** [comment]
All the ground work is in place. Age of Rebellion is a copy and paste of Edge of the Empire. Force and Destiny is ready for work with placeholders and basics. If you are still interested in assisting with getting these two additional books in working order let me know.

Best,

**Comment by BahamutDragon** [comment]
No further user feedback. Closing out this inactive issue.
