### ISSUE TITLE
PHB2 and Unearthed Arcana errors

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#230]
PHB2: 
* Duskblade has the wrong BAB table. Has +0 BAB at Level 1, should have +1 BAB at Level 1.  

Unearthed Arcana: 
- Battle Sorcerer: 
  * Doesn't have Light Armor proficiency.
  * Doesn't have choice of Light or 1-handed Martial Weapon proficiency.
  * Doesn't qualify as a Sorcerer under Class Features or Feats sections

PS: Any ETA on when the Green Ronin Advanced Players Manual race customization rules will be implemented?

**Comment by BahamutDragon** [comment]
To answer your issues in order:

1) I wonder how that slipped by. Duskblade is fixed. Will push that in once I address the Battle Sorcerer problems.

2a) I see a properly embedded proficiency call within the existing class file. (ABILITY:Internal|AUTOMATIC|TYPE=ArmorProfLight). I have to ask, how are you verifying the lack of Light Armor Proficiency?
2b) Debating whether to use a Chooser or finite list of options. I have had some poor results with the choosers in the past.
2c) Adding SERVESAS:CLASS|Sorcerer to the class line will fix the problem.

3a) First request for any implementation of Green Ronin's Advanced Players Manual race customization rules that I am aware of.

Customizers present a difficult issue on how to best present something easily understood to obtain the desired results. 

## Issues implementing
PCGen requires a race, without one you encounter all sorts of eccentric and bizarre behavior. 
Since a race is required, a name for the race is required. What do you call the "customized race"?
The pcgen team did something similar for the advanced race guide.

If you still desire this feature to create a customizable race with these limitations, then please open another issue for it.

**Comment by LiaungYip** [comment]
If this is relevant:

The official PCGen data files for DnD 3.5e and Pathfinder are coded to allow customisation of racial traits. For example, there is code to support a "marine dwarf", a subtype of dwarf whose combat bonuses vs. giants are replaced by combat bonuses vs. water elementals.

I did a writeup of this at http://www.penwatch.net/cms/?p=481 which explains how it's done.

**Comment by BahamutDragon** [comment]
I feel important, not often I have more than one person join the conversation in issue threads.

@GamerGoddessDin - The requested fixes are all in. For the Green Ronin inquiry, reviewing the customization options, they appear to be a compiled list of existing options with points appended, and then specific racial restricted options. Plausible to include. 

@LiaungYip - Many of the newer sets I had a hand in creating use the standards the pcgen team uses. Racial trait swapping is set up in my sets, that is not a concern. The system is basically a laundry list of generic add-ons any race may take, and then has a list of race restricted add-ons. Less swapping and more just pick and choose. Thank you for the article link. I sincerely hope more read that and feel inspired to join our coding home brew community.

**Comment by GamerGoddessDin** [comment]
For the Light Armor on the Battle Sorcerer I referred to the class features page as well as the character sheet tab. The class features page didn't mention the proficiencies at all and the sheet had the standard Sorcerer's armor (lack of) proficiency description on it.

PS: The specific race customizations I like to use are the "Gain 5 points by adding a Favored Class to a race that doesn't have one", "Gain Weapon Familiarity with one Exotic Weapon", and "Gain Resist 5 to one Energy Type". As for customized race's names you just use the name of the base race that the player modifies, for instance if I were to add the aforementioned modifications to a Human base race the character's race name would be Human. (I mostly use the race customization rules to get balanced backstory benefits. Trained from a young age to be [Favored Class] using [Exotic Weapon] in a region that has large amounts of [Energy Type] in the air all the time. That kind of stuff, usually use either Heat/Fire or Cold/Ice.

PPS: The Draconic Feats from Complete Arcane aren't there yet and I'd really love it if they were by the time the next update comes out.

PPPS: In case it wasn't obvious I discovered most/all of these errors/missing things while trying to build a character that used them. I want to build the Dovahkiin in D&D 3.5.
