### ISSUE TITLE
Adaptive Learning adding excess points/not giving appropriate number of selections

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#240]
When I select Adaptive Learning it only allows for one of the 4 skill choices it should thus requiring me to add it three more times for the proper effect. Each of these additions of it are adding the full 4 Ability Point cost resulting in an excess of 12 points.

Possible fixes:
1. Leave it needing to be added 4 times for full effect but reduce the point addition of each to 1.
2. Make the first addition give the full 4 Skill selections.

**Comment by BahamutDragon** [comment]
Option 2.

**Comment by GamerGoddessDin** [comment]
Just curious: Is it helpful at all when I suggest methods of fixing things like this?

**Comment by BahamutDragon** [comment]
Yes, it does help.

In some cases, knowing how you want something can help. This actual case, the error was in my code. I omitted the SELECT:4 which is why it defaulted to 1. Mistakes happen. No promises the data offered is 100% perfect. 

For tougher items where different results can happen, such as issue #239, having an idea of your ideal resolution is handy. 

Best,
