### ISSUE TITLE
Green Ronin APM Race level implementation query

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#245]
Would it be possible to make various special race "classes" show up in the list when the Racial Hit Dice race trait is taken that have the class skills and hit dice of the race's favored class?

**Comment by BahamutDragon** [comment]
Sorry mate, the email request was about this issue. We need to discuss
how you visualize this working.

I have a working conceptual idea of how to implement your request, but I
do not think it is what you have requested, or at least how I read the
query. There are also some other logistics I want to run by you, but not
flood the watchers list with.

I have a patch for issue #246. I had to re-read it a couple of times to
figure out what you meant. I accidentally sent the email request to that
one due to that.

Best,

On 7/21/2015 2:04 PM, GamerGoddessDin wrote:
>
> Would it be possible to make various special race "classes" show up in
> the list when the Racial Hit Dice race trait is taken that have the
> class skills and hit dice of the race's favored class?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BahamutDragon/pcgen/issues/245>.
>

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by BahamutDragon** [comment]
Best solution implemented.
