### ISSUE TITLE
Green Ronin APM Racial Hit Dice on Human base has no class skills

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#248]
Untested with non-Human base races but with a Human base the only class skill is the Literacy non-skill. The testing character used the Duskblade imposed Favored Class before adding the APM HD Humanoid level/s and thus should have had the same class skills.

**Comment by BahamutDragon** [comment]
Hi Mate,

Here is my understanding of the regular D&D 3.5e rules.

Favored Class is based upon multi-classing, and has nothing to do with class skills. Favored Class is simply a mechanism by which you can take a specific class and not have it impose the 20% experience penalty for multi-classing. Otherwise, multi-classing requires you to keep all class levels within 1 level of each other or take a cumulative 20% penalty for each class out of compliance to your experience accrual. If you take levels in your favored class, and have another class, the favored class bypasses that restriction. 

Humans and Half-Elves do not have a specific favored class, allowing them the most versatility to multi-class. They treat their highest level class as their favored class.

Most racial hit die (HD) levels have no inherent class skills. Those racial HD classes are taken directly from the official sets, and I hope follow the existing guidelines. Creatures that do have racial HD normally have a small list of racial class skills inherent to that specific race, not the HD classes. 

Humans and other 1 HD races do not have any inherent racial class skills, since they normally swap the first HD to the actual classes they take. Which explains why the racial class skills were not included, since they only level in actual classes in the main rulebooks. 

If the APM has a section that alters those rules ,that I missed, please let me know. Otherwise, the system is operating exactly as the existing rules state they should.

Best,

**Comment by GamerGoddessDin** [comment]
Following is the copy-pasted note from the bottom of Table 2-3 Additional Race Points in the Green Ronin APM that relates to the various Racial Hit Dice options: 
"When determining racial Hit Dice class skills for a race that does not ordinarily have racial Hit Dice, use the skills of their favored class, plus any skills in which they receive a racial bonus. For races which already have racial Hit Dice, use the race’s class skills as listed in the MM."

**Comment by BahamutDragon** [comment]
That helps for the rules. Thanks.

Unfortunately, pcgen has some limits of what can be done.

It is possible to "grant" the requested class skills. This downside is it will be via the global grant. Which means you will have the Duskblade skills, but if you take a level of say Fighter, the Fighter will have both Fighter and Duskblade skills.

As long as this limitation is understood, I will implement it. Anything beyond that, you need to talk with the pcgen team.

Best,

**Comment by GamerGoddessDin** [comment]
Sounds alright to me, might want to add a mention of this to whatever option does the granting.
