### ISSUE TITLE
Green Ronin APM/Unearthed Arcana Battle Sorcerer can't select Bastard Sword proficiency after gaining familiarity, only before

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#254]
Might be something about backwards requirements on the Battle Socerer weapon proficiency list or the like.

**Comment by BahamutDragon** [comment]
I had to re-read the issue a few times before it made sense. 

Interesting thing about the progression of the bastard sword and the code involved. It is only one of two weapons that actually changes how it can be used based upon an Exotic Training by feat. The current code is quite clever, it addresses the heart of the issue which is how many hands used.

Here is the battle sorcerer proficiency chooser:
  `CHOOSE:WEAPONPROFICIENCY|TYPE=light,TYPE=martial|TYPE=onehanded,TYPE=martial|EQUIPMENT[TYPE=light,TYPE=martial]|EQUIPMENT[TYPE=onehanded,TYPE=martial]`

To break that down
Proficiency Type must be Light & Martial, or OneHanded & Martial
or
Equipment Type must be Light & Martial, or OneHanded & Martial

Oddly enough, none of those will catch the only change triggered on the bastard sword. The Wield Category is changed from TwoHanded to OneHanded, not the type.

Need to add WIELD= to the mix to actually catch the change. That is all academic though since the code on the proficiency should be a valid selection in that chooser:

Proficiency:
`Sword (Bastard)			TYPE:Exotic.Melee.OneHanded.Martial.ExoticMelee.MartialMelee`

Even though the Bastard Sword is not Exotic, the code should already allow the selection based upon the OneHanded & Martial. Worse, the code attempted to address this is failing. Leading this to be a pcgen team issue.

**Comment by GamerGoddessDin** [comment]
Well, at least we have a temporary workaround in place until the PCGen team gets whatever the root of the problem is fixed.

I'll just have to keep selecting the Bastard Sword proficiency from the Battle Sorcerer before adding in the Weapon Familiarity.

**Comment by BahamutDragon** [comment]
I shall let you notify the pcgen team (http://jira.pcgen.org) of the issue, since you can describe the issue in greater detail. 

I think this is a 'code bug' with the choose system and maybe something deeper since the removal of the bastard sword does not make sense after taking familiarity.

**Comment by GamerGoddessDin** [comment]
I honestly don't really understand what's happening behind the scenes there. I just know that if I choose the Bastard Sword option in the Battle Sorcerer's proficiency list before taking familiarity it works as intended (aside from being able to select what at the time should be considered an Exotic weapon) but if I take the familiarity first then the now Martial weapon Bastard Sword is no longer on the list.

My first thought was that somewhere in the code a sign was flipped the wrong way so that the Bastard Sword qualified for the list when it's an Exotic but not when it's a Martial instead of the other way around but apparently I was mistaken.

I think you probably understand the internal stuff there better so you should probably be the one to report it but feel free to quote me if you think it'll be helpful.

**Comment by BahamutDragon** [comment]
https://pcgenorg.atlassian.net/browse/CODE-2874
CODE-2874	CHOOSE:WEAPONPROFICIENCY|EQUIPMENT[WIELD=x] failure

**Comment by BahamutDragon** [comment]
Unresolved until PCGen team acts on the code bug. Notation in the set added. Closing this out.

**Comment by gamotria** [comment]
Hi friend! 


I have   amazing  news for  you, you'll love it! Please read it here <http://book.wodingdong.com/uezeef>

See you around, mdatz20
