### ISSUE TITLE
Request: [3.5] Implement the Appearance stat from Book of Erotic Fantasy

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#255]
If needed I could aid in acquiring a PDF copy of the book.

**Comment by BahamutDragon** [comment]
Publisher Valar Project, Inc.?

**Comment by BahamutDragon** [comment]
This request presents a problem. Attribute stats are controlled by special files within the gamemode folder. In order to "add" a stat requires adding it directly to the gamemode, or making a new gamemode. In this case books loaded will not matter.

This is filed under a 35e request, yet the only 35e gamemode under my control is Bahamut35e. For this request, I think the only solution is to create a 35e_Erotic_Fantasy gamemode. If the book is ever coded up, then it would only be available under that gamemode. Meets your request for a stat, and will not alter the existing characters.

**Comment by BahamutDragon** [comment]
New gamemode created.

**Comment by BahamutDragon** [comment]
New Code allows for the lack of a gamemode. This support will be in 6.6 only.
