### ISSUE TITLE
Races of Faerun Aarakoa have no options in the choice list after the region selection

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#263]
title

**Comment by BahamutDragon** [comment]
Do you have a book reference that would give me the answer as to what choices should be presented to you? Another contributor coded up the regional rules and has not been actively contributing for some time.

**Comment by GamerGoddessDin** [comment]
Not really sure what should be there. I'm guessing probably the same stuff that's in the regional benefits for other characters that choose the same region but Aarakoa is the first race that's asked me to choose a region immediately upon choosing the race so there may be more to it than that.

**Comment by RonCKFish** [comment]
The Races of Faerun book was superseded by Player's Guide to Faerun. I don't think I coded most of it as it would of have to be commented out for use. I do not recall coding the aaracokra.Sorry,Ron                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: GamerGoddessDinSent: Saturday, August 15, 2015 23:36To: BahamutDragon/pcgenReply To: BahamutDragon/pcgenSubject: Re: [pcgen] Races of Faerun Aarakoa have no options in the choice list after the region selection (#263)Not really sure what should be there. I'm guessing probably the same stuff that's in the regional benefits for other characters that choose the same region but Aarakoa is the first race that's asked me to choose a region immediately upon choosing the race so there may be more to it than that.

—Reply to this email directly or view it on GitHub.

**Comment by BahamutDragon** [comment]
The revision to the D&D core rulebooks incorporated several of the feats that were previously exclusive to specific character regions (such as Stealthy) into the Player’s Handbook, thus making them available to all characters. In addition, experience has shown that the complicated interaction of race, preferred class, and character class made it difficult for players to navigate the regional feat system and find the right character combination to choose the feats they wanted.
The revision to the character region system presented here incorporates four major improvements to the previous version. First, the cross-referenced tables make it much easier to locate region and feat correlations you want for your character. Second, the elimination of the preferred class step should reduce the number of “false starts” that resulted from the previous region system. Third, additional regional information from several other 3rd Edition FORGOTTEN REALMS supplements (such as Races of Faerûn, Unapproachable East, and Underdark) has been incorporated into the system. Finally, regional feats have deliberately been made more attractive choices than corresponding nonregional feats in order to reward you for grounding your character in the FORGOTTEN REALMS setting.

The Stormhorns: Driven from their home in the Star Mounts by a dragon, many aarakocras founded new aeries in the Stormhorns of Cormyr. Knowledge (Cormyr local).

That is coded up properly for the race. The Races of Faerun version forces a region selection immediately. I will disable that, and it will then work as expected.
