### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Wemes** [BahamutDragon/pcgen#294]
I'm trying to fix up the wizard illusionist improved minor illusion ability. I've got it so it will grant the cantrip automatically, however I'm trying to figure out a way to implement the rule that if you have the cantrip already you can pick another one. It works now that if the user just removes the minor illusion cantrip from the pool it will still be there and the user can select another one. Does anyone know a way for the ability to do this automatically so that the user doesn't have to remove it manually?

Another question: as CAST tags are currently some classes have them spelled out and some just have placeholders to enable spells for the sheet. What if we did something like for each CAST tag use something like: 
CAST:0,SpellSlotsLVL1,SpellSlotsLVL2,SpellSlotsLVL3,SpellSlotsLVL4...
We could do this for all spell casting classes and it should keep spell slots it consistent when multiclassing. I can admit that it might be confusing when multiple items on the character sheet have the same cast numbers, but a note that all spell slots are shared would help clarify it. Things would have to be different for the warlock cast chart too as it doesn't add to multiclassing spell slots.

**Comment by BahamutDragon** [comment]
Mate,

For the first point, bit of complex coding, though quite possible. Have
you managed to come up with a solution? I have two working conceptual
ideas that would get the results without producing an endless loop
situation.

For the second point, I would be against that solution for three reasons:
1. Confusing to those who multi-class. No method to efficiently convey
any messages to the end user about specific items without a lot more work.
2. Cast also controls when spell levels are available when KNOWN is not
being used.
3. Not a proper solution, just another hack until a proper solution is
implemented.

The whole casting situation is a complicated mess. We have CAST, and
KNOWN, but really need to designate when a particular class can cast. I
have been holding off for the pcgen team improvements in the hope that
the new formula system replacement and character sheet changes will be
able to be used to affect a proper solution.

If this really needs a go right now, then the current solution is to
re-write the spells output sheet.
Change the "CAST" display to "Can Cast" and make 0 display "No" and 1
display "Yes"
Then add a new header for the spell block to show total spell slots
available. With the slot variables brought in from the Spell Slots ability.
Make sure CAST "1" is in place for the correct levels for all current
classes involved.

I would rather wait for the new formula implementation to prevent any
extra work redoing everything. I am a rather big fan of only doing the
work once if possible.

Do not misconstrue my intent though. If you feel up to the task of
altering the OS to what the proposed proper course of action, then do so. 

Best,

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by Wemes** [comment]
Thanks for the input. I haven't figured out a way to get the first point, I'd be glad to try your suggestions. 

On the second if that's what you think that's fine. I'm just trying to run things through my head about getting this to go with the rules proper. 5e has already thrown the way PCGen works out of whack with changing the nature of spells and preparing them and I'm sure it's hard for the PCGen team with 5e not having any sort of OGL-like license. Hopefully at some point something can be figured out.

**Comment by BahamutDragon** [comment]
Mate,

These should help you get the desired results. Adjust for actual object names.

Concept 1: Dynamic - UI display version
BONUS:VAR|POOL_WizardCantrip|1|PREMULT:2,[PREABILITY:1,CATEGORY=x,CantripNAME],[PREVAREQ:CantripNAMEGranted,0]

Grants an additional pool point if the Cantrip is manually taken. Nothing else happens.

DEFINE:CantripNAMEGranted|0
BONUS:VAR|CantripNAMEGranted|1|PREMULT:1,[!PREABILITY:1,CATEGORY=x,CantripNAME],[PREABILITY:1,CATEGORY=x,CantripNAMEGranted]

ABILITY:Internal|AUTOMATIC|CantripNAMEGranted|PREVAREQ:CantripNAMEGranted,1

This triggers if the ability is removed, or does not exist. Once that happens, cantrip is granted, pool is not increased.

CantripNAMEGranted
CATEGORY:Internal
ABILITY:Wizard Cantrip|AUTOMATIC|CantripNAME

This version assumes the end result is displaying in the UI.

Concept 2 Non UI method is just a simple adjustment: Add the cantrip SPELLEVEL/SPELLKNOWN tag with |PREVAREQ:CantripNameGranted,1 appended instead of the ABILITY tag. Then change the BONUS Var to BONUS:VAR|CantripNameGranted|1|!PREABILITY:1,CATEGORY=x,CantripName

There is a third concept, but the assignment is static and not something I would recommend for this case.

**Comment by BahamutDragon** [comment]
@Wemes any update on this?

**Comment by Wemes** [comment]
Hi, yeah thanks to your suggestions I got something to work as the rule intends. I'm going through the warlock before I check anything more in (warlocks are tricky, they have all those options and invocations)

**Comment by BahamutDragon** [comment]
Is this all resolved then?

**Comment by Wemes** [comment]
Yeah, I guess I should probably close it then.
