### ISSUE TITLE
[Dnd 3.5] Hellfire Warlock Eldritch Blast damage progression still don't stack with Warlock's level

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#303]
For 15 lvl of Warlock 12 and 3 lvl Hellfire Warlock it still shows Eldritch Blast damage as 6d6 as for Warlock 11 (when it should be 7d6 which Warlock gains on 14th level) and Invocation progression is also now do not stack (i see -2 greater invocations)

**Comment by BahamutDragon** [comment]
Pesky ADD tag. Not retroactive on class levels. If you level down the Hellfire Warlock and level back up, the numbers will be correct. New characters, work fine, which is what I tested the last patch on. Old characters will not work. Since the ADD of spellcaster for a warlock is pointless, an alternative fix to make this be retroactive can be implemented. Just realize not every fix can be retroactive for existing characters.
