### ISSUE TITLE
[System Request] Final Fantasy Pathfinder

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#308]
The content itself is all on http://www.finalfantasyd20.com/ffd20/index.html

**Comment by BahamutDragon** [comment]
Mate, 

That is a bit daunting to even consider.

The referenced site has multiple resource links, with the primary guide book weighing in at 900+ pages of fan content. Which breaks down to 300+ pages of spells, 250+ pages of classes, 60 pages of prestige classes, 47 pages of races, and 32 pages for feats. The system itself is built upon the d20 Pathfinder rule system base, with a minor hybrid rule set layered on top of that. I would need some serious help in one fashion or another to get this to a point it would be usable, assuming the goal is a standalone source book. At a rough guess this looks to be at least a 2 to 4 month project for a single bloke, 1 month minimum if all you wanted was text and no implemented changes (stats, skills, attacks, etc.). Biggest time consuming part is converting the text into pcgen tag readable format, and then reading those objects for any permanent bonuses that require implementation.

For a quick example of a simple conversion:
`Thick-skinned: A bangaa's tough and scaly hide grants a +1 bonus to natural armor.`

Becomes:
`Thick-skinned	KEY:Bangaa ~ Thick-skinned			CATEGORY:Special Ability	TYPE:Bangaa Race Trait.SpecialQuality	SOURCEPAGE:p.15	DESC:A bangaa's tough and scaly hide grants a +1 bonus to natural armor.	BONUS:VAR|AC_Natural_Armor|1|TYPE=Base`

Check out the time line for World of Warcraft (400 page source book). That is a d20 system as well, re-using the 3.5e system for most of the framework. It has been about two months of work, and only basic text placeholders. Anticipate another month before the bonuses are all in place.

I also have a concern this will overlap the anticipated pcgen program changes to their new formula system.  

This will have to be a master branch project only.

Best,

**Comment by GamerGoddessDin** [comment]
From what I was reading all the sources other than the main book on there were just separated sections of the main book which may or may not have been updated since the last time the main book was updated.

Not complaining or suggesting that you're overestimating the amount of time it will take to implement just thought it was worth mentioning. Thanks for at least considering it for a future addition.

**Comment by BahamutDragon** [comment]
Mate,

The time estimate was based only on what I saw in the main book. 

Time consuming extras:
It has racial trait swapping; class archetypes; separate favored class bonuses; various selection pools for races, classes and feats. Anything that requires a selection from the user.

The extra functionality takes up considerable time to implement. The time factor will change as coding progresses. The more complex something is, the longer it takes to set it up.

I will be able to borrow the existing code from the pcgen official sets for at least the skills and eidolon coding. Looks like equipment is left unchanged and can be ported in.

If you want something in particular, like a specific race or class, that can be done in an hour usually. 

Best,

**Comment by BahamutDragon** [comment]
724 insertions(+) Approximate 1 hour of work.

**Comment by BahamutDragon** [comment]
@GamerGoddessDin basic races and classes now working. Speak up now if you want any particular class up and running. I am going to work on equipment next. Still a lot of work to go.

**Comment by GamerGoddessDin** [comment]
Make sure the Red Mage class and Gria race are fully functioning.

BTW: Do you have any idea how to make the GitHub app download and maintain 2 branches of the same repository separately? Recently downloaded the beta build of PCGen in order to have access to the newer "official" Pathfinder source files and would like to be able to download the branch for FFPF separately to import into that install rather than the Live build I use for 3.5.

**Comment by BahamutDragon** [comment]
Mate,

Can you please clarify what you mean by fully functioning? I have found that to be one of the most vague of definitions to deal with. Often the person making the request has different ideas of what that means. The coding involved with both of those requests can be completed in a span of a few hours, or over a week depending on your definition.

Fully functional to me for just the Gria:
Racial Trait swapping is set up properly (60-120 minutes)
Racial Traits change numbers of the sheet (60 minutes)

For the red mage:
Spell support (30-90 minutes)
Class features load without errors (45 minutes)
Class Features progression and displayed (20 minutes)
Class features that grant choice pools (30 minutes)
Spell Point display (30 minutes)
Class features implemented (2 hours)
Archetype Support with Archetypes implemented (5+ hours)
Favored Class support for Red Mage (2+ hours, contingent upon class features being implemented)

As you should be able to see, fully functional is well over 15 hours of work.  Giving a generous 2 hours a day that is 7 days or so...Please narrow down what you actually need and I will see about getting that set up. (What is the absolute minimum you require for your game?)

The set is currently between 5% to 10% completed. The three month time frame is still pretty much on target. When I said basic, I meant, you can load the sets without error, but a lot of functionality is not anywhere near completion. All the races display the traits, grant movement, stats and languages. The Archer class is the only class that will display class features currently, the rest will cycle up base attack bonus, the saves, and grant skill points and class skills.

For the question posed:
I do not use the github app. I found it practically useless for the work I do on the project. I would suggest a proper git client. The pcgen team uses the standalone client SourceTree, and I have been convinced of the utility of the shell integration git tool tortoisegit. 

I would caution against having two copies of the same repo being accessible to the same instance of pcgen, even if they are different branches. You would have duplicate entries which would cause headaches for you. I would recommend learning and using the checkout function in git to use the branch you need before you run pcgen. Or if you really need two different versions, Install pcgen to two different locations and have the extra data folder point to your repo clone..

I may be mistaken, but it sounds like you are not taking advantage of the multiple data folders option in pcgen.

You can easily do this:
pcgen main install (c:\program files\pcgen)
pcgen homebrew (c:\pcgen\homebrew)

From the readme.md file:
The better method is to install GIT and a GIT Client, and clone the repository to a location outside of the PCGen installation directory. Then open PCGen, go to Tools>Preferences and in the Location tab under the PCGen drop-down, change the folder path of "PCGen Vendor Data Directory" or "PCGen Homebrew Data Directory" to the directory you cloned the repo into. This allows easy updates when they happen (via a git pull). It also saves bandwidth since you are only downloading changes, not the whole repository

Once you learn how to do the git checkout (change active branch) you will save space and be happier. (Pull will keep the branch up to date)

Best,

**Comment by GamerGoddessDin** [comment]
I have 2 separate installs of PCGen, one Live and one Beta. Currently the Live version is set up to use the current 6.04.01 branch synced using the GitHub app as it's Vendor Data Directory while the Beta version is still purely set up for use with the default included datasets.

What I intended to do is have a separate copy of the repo synced with the FFPF branch set as the Vendor Data Directory for the Beta Version.

I may look into getting a different client though.

Currently waiting on a response from the DM on what level the FFPF campaign is at and how fast it's advancing.

**Comment by GamerGoddessDin** [comment]
So just heard back from the DM. They're currently Level 2 however they're advancing pretty quickly and may be up to Level 4 in just a couple sessions. As the sessions occur whenever enough players are available for a campaign with this group it's hard to guesstimate how long IRL that will be.

**Comment by BahamutDragon** [comment]
After testing, the Gria and Red Mage appear to be working correctly.

**Comment by GamerGoddessDin** [comment]
I'd like to get the Fire and Lightning Materia added in the next batch if possible.

PS: SourceTree is pretty nice and did what I needed it to.

**Comment by BahamutDragon** [comment]
Adding a 'please' and 'thank you' really makes my day when being asked to add things. It is the little things that makes one feel appreciated in their undertakings.

Materia is one of the easier things to code, you may want to try your hand at coding up the other materia.

**Comment by GamerGoddessDin** [comment]
I suppose I could try my hand at that. Though I'll probably have to see the code for a couple of them to study first... I don't exactly have any experience coding datasets for PCGen.

**Comment by BahamutDragon** [comment]
Spell materia is already coded. Check the master branch. https://github.com/BahamutDragon/pcgen/commit/d478a92d7413810d13d0996697fb327d599aa130

**Comment by BahamutDragon** [comment]
Any progress on the remaining materia?

**Comment by BahamutDragon** [comment]
@GamerGoddessDin any progress with the materia? Anything I can assist you with?

**Comment by GamerGoddessDin** [comment]
Hadn't actually gotten around to working on them at all. Been distracted by other things.

Speaking of distractions, I still need to make a couple fixes to things in my 3.5 campaign on Roll20.

**Comment by BahamutDragon** [comment]
All requested items added. No further requests added or feedback in a few months. Closing out this inactive issue.
