### ISSUE TITLE
[3.5] [Eberron Campaign Setting] Artificer Bonus Feats not being added.

### ISSUE THREAD

**Issue by GamerGoddessDin** [BahamutDragon/pcgen#322]
The Scribe Scroll, Brew Potion, and Craft Wondrous Item Feats are not added at Levels 1-3 as they should be. I've not tested further levels as of yet but I suspect they are the same.

**Comment by BahamutDragon** [comment]
Fixed as of https://github.com/BahamutDragon/pcgen/commit/d6fbdf601caffc468f2b463559baae5b3b3d7d0c and fbe291bbf486e317d46fce7fcdc48c623101109b

**Comment by GamerGoddessDin** [comment]
Just a note, not necessarily something you need to change, but the Artificer according to RAW is neither an Arcane caster or a Divine caster. It's actually meant to be a completely different thing, basically they're the high fantasy equivalent of a technomancer/gadgeteer.

Again, you don't need to change anything regarding this if you don't want to it's just a little factoid I thought you might be interested in.

**Comment by BahamutDragon** [comment]
The change was prompted by the fact an Artificer is unable to qualify for any Metamagic feats. Seemed prudent to make a minor change to allow the artificer to acquire other metamagic feats. The eventual solution is to re-code those feats to the correct "caster level" query instead of the current Arcane/Divine set up.
