### ISSUE TITLE
[3.5] Allow adaptation versions of Tome of Magic Prestige Class "Anima Mage"

### ISSUE THREAD

**Issue by darkmaster89** [BahamutDragon/pcgen#327]

**Comment by BahamutDragon** [comment]
Mate,

Helps if I have an idea what you are actually requesting.

After a look at Tome of Magic all I came across was this small section:

ADAPTATION
Anima mages needn’t exploit vestiges to gain power—the
vestiges could volunteer the added powers to an anima
mage in recognition of his spellcasting ability.*You could**
**also relax the prerequisites to open this prestige class to any**
**spellcaster—or even a psionic character.*
A more sinister version of the anima mage could bind
fi ends or celestials instead of vestiges. To do so, the character
would use the soul binding ability as described on page 10.
An anima mage who succeeds in coercing such an outsider
(DC equals the creature’s CR + its HD) gains a bonus spell
slot, as noted in the exploit vestige ability description, but
no special abilities.

Is the request to relax the class entry requirements and/or increase 
psionic progression? If not, then can you provide at least a book title 
and page number or a web link if unofficial, for this variant?

Best,

  darkmaster89 wrote:
>
> —
>

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by darkmaster89** [comment]
Ops, sorry about that it was a bit of a rushed post. The request was to relax the entry requirement and to add psionic progression to the Prc. Thank you for your time

**Comment by BahamutDragon** [comment]
Class now allows any Divine, Arcane or Psionic level 2 spell, and allows progression in any spellcaster class taken.
