### ISSUE TITLE
[Request] Add description for wand spell in inventory

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#377]
Is it possible and does it make sense to add description to wand (perhaps staff, scroll) that is in one's inventory? Right now it only contains spell name, class from what that spell is taken and caster level. While this info is enough to look for this spell and see DC, duration, variables, damage, range etc, it would have been much more handy to see this in description

**Comment by BahamutDragon** [comment]
Mate,

This appears to be a Big project for little return. 

Adding an SPROP for each item is a time consuming project. You would have to look up the spells individually.
What is the format?

It would be better to use the SPELLS tag to grab that information. That would appear on the back pages on the character sheet. 

Big project though and not something I would volunteer to handle. If you want to volunteer and do it yourself, the formulas are below.

Caster level is the minimal level to cast the spell (unless specified otherwise - in which case the cost needs to be altered accordingly)
1 for 1
3 for 2
5 for 3
etc.

The DC formula is 10 + Spell Level + Minimal stat to cast the spell
0th and 1st is +0
2nd and 3rd is +1
4th and 5th is +2
6th and 7th is +3
8th and 9th is +4

Examples
Wand of Magic Missile
SPELLS:Wand of Magic Missile|CASTERLEVEL=1|Magic Missile

Wand of Fireball
SPELLS:Wand of Fireball|CASTERLEVEL=5|Fireball,13+1

You can add TIMEUNIT=Charge and TIMES=1 if you would like, but less is more in some cases.

**Comment by shadowfury** [comment]
Hi, thanks i'll take a look at that. Though i didn't mean to add descriptions for all existing items, but rather for only one, custom. There is an option to select simple wand and add spell to if from some class some caster level. And i was suggesting to add info only for that case, without affection tons of other items from different books etc

**Comment by BahamutDragon** [comment]
Mate,

That is well outside my power. The item customizer is a code construct of the PCGen program. You need to talk to the PCGen team about altering that.

Best,

**Comment by FerretDave** [comment]
Greetings,
Note that I've been adding short 'SPROP' tags to various (predefined)
scrolls and wands,
in 35e\wizards_of_the_coast\core\dungeon_masters_guide\dmq_equip.lst and
the Spell Compendium, but pretty much onlyadding them as I need them...
'mount' is one example, since reading the 'Critical Failures' novels,
that's become a must-have spell ;-)

There's no easy way to get it done automatically unfortunately though. Easy
enough to code them up yourself though.

Cheers
Dave

On 5 February 2016 at 17:09, Bahamut <notifications@github.com> wrote:

> Closed #377 <https://github.com/BahamutDragon/pcgen/issues/377>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BahamutDragon/pcgen/issues/377#event-540916265>.
>



-- 
            oxxxxxxx{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;>
