### ISSUE TITLE
5e Prepared Wizard Spells

### ISSUE THREAD

**Issue by tehboss** [BahamutDragon/pcgen#378]
Not sure if the issue is your resources or PCGen. Wizards should be able to prepare any number of spells (regardless of slot) in combinations of slot levels available equal to the number Wizard levels plus Intelligence bonus. So if I have a Level 1 Wizard with an 18 Intelligence, he should be able to prepare 5 Level 1 spells. At level 3 he should be able to prepare 7 spells of any combination of 1st and second level spells.  Currently the prepares list limits me to 1 spell at first level. I went to 3rd level and it still only lets me prepare 1 1st and 1 2nd. SRD data is the same. Not sure if the information I copied into the other folders (non-data) changed something for this. If this is a PCGen issue, I can send the bug to PCGen. The table shows only 1 prepared spell available per level.

**Comment by BahamutDragon** [comment]
Mate,

I can alter the spell number. The problem is the readied system of 5e is not compatible with the memorized / cast system that is build into pcgen. Two completely different systems. I would have to hack one method or another to get the correct results. Either method will be misleading though.

PCGen supports two tags: CAST and KNOWN. 
Cast = number of memorized spells you can prepare or represent number of spell slots.
Known = number of spells you can have.

The user interface has three tabs set up for a 3rd edition model: 
Known Spells (Is limited by the KNOWN tag if MEMORIZE:NO is used). This is all the spells available to the character.
Prepared Spells (Is limited by CAST, this is used for Wizards memorizing spells)
Spell Books (Is meant to hold spells from various books)

If you want to have a prepared list, it might be best to set up a spellbook and call it prepared spells.

I will enable the spell slots to use the CAST tags. This will not give the full allotment of available "prepared spells". It will match the total number of slots for casting for ALL casting classes though.

Best,

**Comment by BahamutDragon** [comment]
Mate,

I just had an idea. I will grant level 10 slots that will grant the difference you need to add the number of spells to the prepared list. Make sure you enable the "Allow Use of Higher Level Slots" to make use of the feature.

Best,
