### ISSUE TITLE
[5E] Weapons on character sheet show improper to-hit and damage

### ISSUE THREAD

**Issue by nigelboid** [BahamutDragon/pcgen#456]
PCGen 6.06 and BahamutDragon/pcgen 51ae71a

Weapon blocks on character sheet seem to follow 3.5/Pathfinder to-hit and damage rules rather than 5E rules.

Specifically:
- allows two-handed fighting with heavy weapons (no Dual Wielder feat)
- shows damage bonus for off-hand (no Two-Weapon Fighting Style)
- reduces to-hit for off-hand (one-handed and two-weapon)

I believe this is a correct summary of the current rules in the PHB:
- To hit= d20 + ability modifier + proficiency bonus, regardless of hand
- Damage= weapon die (or dice) + ability modifier
- If wielding two light weapons, use bonus action to hit with second weapon (no damage ability modifier unless negative)
-- Dual-Wielder gets to use non-light weapons
-- Two-weapon Fighting Style adds back the positive ability modifier for damage on the bonus action attack

Is this a bug, a feature, or did I improperly install something?

Thanks!

P.S. Ranged weapons also seem follow non-5E range rules (instead of normal for short and disadvantage for long).

**Comment by BahamutDragon** [comment]
Mate,

Although I created the initial 5e character sheet from the existing 3.x
sheet; what I had has been given to the pcgen team to improve upon.

Yes, it is either a bug or a feature improvement. I could attempt to
clean it up, but that is not a very strong area. You will have better
results if you ask the pcgen team to address it, since they have the
base 5e stuff and have already fixed issues I could not tackle. Use the
pcgen tracker system jira.pcgen.org. The classification will be output
sheet and since it is asking for changes, use feature request.

I will address the sheet update, only if they give you a lengthy time
frame to get it resolved on their end.

Best,

On 3/24/2016 3:22 PM, Igor S. Livshits wrote:
>
> PCGen 6.06 and BahamutDragon/pcgen 51ae71a
> <https://github.com/BahamutDragon/pcgen/commit/51ae71a09b79b0b8b5aef58959da9ecd347bb412>
>
> Weapon blocks on character sheet seem to follow 3.5/Pathfinder to-hit
> and damage rules rather than 5E rules.
>
> Specifically:
>
>   * allows two-handed fighting with heavy weapons (no Dual Wielder feat)
>   * shows damage bonus for off-hand (no Two-Weapon Fighting Style)
>   * reduces to-hit for off-hand (one-handed and two-weapon)
>
> I believe this is a correct summary of the current rules in the PHB:
>
>   * To hit= d20 + ability modifier + proficiency bonus, regardless of hand
>   * Damage= weapon die (or dice) + ability modifier
>   * If wielding two light weapons, use bonus action to hit with second
>     weapon (no damage ability modifier unless negative) --
>     Dual-Wielder gets to use non-light weapons -- Two-weapon Fighting
>     Style adds back the positive ability modifier for damage on the
>     bonus action attack
>
> Is this a bug, a feature, or did I improperly install something?
>
> Thanks!
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/BahamutDragon/pcgen/issues/456>
>

-- 
~BD
https://github.com/BahamutDragon/pcgen
http://games.groups.yahoo.com/group/bd_games/

**Comment by nigelboid** [comment]
Thanks for confirming. I was afraid I merely messed something up. I'll pursue it as you suggest.

I appreciate all your work on this!

**Comment by nigelboid** [comment]
https://pcgenorg.atlassian.net/browse/OS-455

**Comment by BahamutDragon** [comment]
Problem needs to be resolved by PCGen team. Jira exists.
