### ISSUE TITLE
[d&d 3.5] [Draconomicon] Bloodscaled Fury Nonfunctional

### ISSUE THREAD

**Issue by Taiolu** [BahamutDragon/pcgen#481]
I've done some digging around into fixing the issue with no results, however some things have been noticed.

The code references it both as 'Blood Scaled Fury' and 'Bloodscaled Fury', however PCGEN doesn't recognize either as a class, even if added manually (It outright thinks its not a class)

A second less severe note, awaken frightful presence doesn't stick on reload, so you need to reapply the feat every time you want to try and get a level in the class.

**Comment by BahamutDragon** [comment]
Mate,

I need some clarification when making broad statements. When you say "PCGEN doesn't recognize either as a class, even if added manually (It outright thinks its not a class)" that makes no sense. Either PCGen lists it as a class, or it does not. There is no middle ground, the only factor would be not meeting a prerequisite. In which case, knowing which qualification is not working would help 

Which you add "awaken frightful presence doesn't stick on reload, so you need to reapply the feat every time you want to try and get a level in the class." which tells me it sees the class, but you have something messed up. Corrupted files is not unheard of in the past. 

Do you have an error log that may shed some light on this? (F10 bring it up inside the program, otherwise it is located in the main pcgen installation folder.)

In the mean time:
All Class name references have been corrected to the Book name version of Bloodscaled Fury.
Additionally, the DESC:See Text. have all been removed.

**Comment by Taiolu** [comment]
As in it doesn't recognize it as a class, however it is in the list, selecting it does nothing. Even if prerequisites are met.

[log.txt](https://github.com/BahamutDragon/pcgen/files/222717/log.txt)

I tried adding it manually by editing the pcg file, it says 'could not find class: Bloodscaled Fury' this is what I mean by it not thinking it is a class.
The log on boot shows nothing for it, aside from Awakaned Frightful Presence panicking which shows in the first log.

**Comment by BahamutDragon** [comment]
Discovered issues, working around those. Pull the master and give this a go.

**Comment by BahamutDragon** [comment]
Tested and works for me.
