### ISSUE TITLE
unable to load complete divine

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#524]
[errorforcompletedivine.txt](https://github.com/BahamutDragon/pcgen/files/264504/errorforcompletedivine.txt)

**Comment by BahamutDragon** [comment]
Mate,

Download and install - http://www.pcgen.org/autobuilds/downloads/pcgen-6.07.00-SNAPSHOT-full.zip

or grab the 6.06.x branch only

**Comment by nevarim** [comment]
is not included in the last release?

**Comment by BahamutDragon** [comment]
Mate, 

The error you posted indicated you are using the master branch with pcgen version 6.06.00. Master requires the latest autobuild or development release (as stated on the main code page of this repository under the readme.md section). The PCGen team has not done any development releases yet, but have done quite a number of significant changes. If you wish to enjoy the latest cutting edge feature changes, use the autobuild with the master branch. Otherwise use the 6.06.x branch with pcgen version 6.06.00

From what I understand they plan on updating the code base to java 8, redo the user interface in javafx, and replace JEP with a formula parser system. Those errors are just a few of the improvements that have already been implemented, but not supported in 6.06.

Best,

**Comment by nevarim** [comment]
great news and thanks for help :D
