### ISSUE TITLE
in 6.06.00 getting error on character load that Common is no longer spoken

### ISSUE THREAD

**Issue by jagbear** [BahamutDragon/pcgen#535]
When I load the 3.5 files in version 6.06.00 I am now getting the error on character load that Common is no longer spoken.

![loadlanguage](https://cloud.githubusercontent.com/assets/15275167/15447987/7b3f06a2-1f18-11e6-8751-889523c6f447.jpg)

**Comment by BahamutDragon** [comment]
Mate, although my avatar and name are based upon the god of dragons. I personally lack those powers. This is reporting a symptom, but hardly enough to determine the issue. If you want any help from me in this matter, I will need something more, like the error log, or the character file that is causing the issue. 

Best,

**Comment by BahamutDragon** [comment]
Based upon your current pull, I would guess that you attempted to load an existing character, after the subrace changes were removed, instead of automatically granted. I would guess this is a human character, since the only language reported is common. The solution is simple, you need to select the Base Human and the language will be granted once again. If that is the case, there is nothing for me to fix. You simply must apply the base human and the issue will be resolved on your end.

Best,

**Comment by marcalff** [comment]
Encountered the issue as well, when loading an existing character (created before the sub race change), with pcgen 6.06.00.

I confirm that taking feat "Human subrace/Human" grants common, resolving the issue.
