### ISSUE TITLE
[3.5e] All prestige classes from Complete Divine can be picked as if with bypass prerequisites

### ISSUE THREAD

**Issue by shadowfury** [BahamutDragon/pcgen#583]
I remember i did select this feature once, but i disabled it afterward. All prestige classes from other books looks good

PCGen version - 6.06.00 , release date - 29 February, 2016

![image](https://cloud.githubusercontent.com/assets/2230015/18668150/7a68b88e-7f3c-11e6-9305-ca4c8ef7aae9.png)
![image](https://cloud.githubusercontent.com/assets/2230015/18668152/868b165c-7f3c-11e6-8cab-5fe526c95309.png)
![image](https://cloud.githubusercontent.com/assets/2230015/18668222/e94f3dae-7f3c-11e6-9ced-fbb0ced457a0.png)

**Comment by BahamutDragon** [comment]
Mate,

The house rule is not the issue. Several of the prestige classes just include a simple requirements text, and nothing more. When one is doing the sole creation of the majority of data sets, one takes certain shortcuts to make the materials available in a short amount of time. Leaving off the forced requirements has little impact on most users.

Since this is a project for other contributors to participate, adding in prereqs for newcomers is an easy pathway to inclusion. It would be quite rude of this bloke to take away all possibilities of a newcomer to join the fun.

**Comment by BahamutDragon** [comment]
Added prereqs.
