### ISSUE TITLE
Metamagic School Focus

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#612]
Metamagic School Focus Type: General   Can be taken more than once   Stacks Requirements: either ( almeno 1 Spell Focus FEAT, almeno 1 TYPE.Specialist Wizard Special Ability ) Description: You are unusually skilled at modifying the effects of a particular school of magic. Benefit: You may prepare 3 spells from your school per day with metamagic feats applied at 1 level lower than they normally would be. You may take this feat multiple times, but for a new school each time.  Source: Wizards of the Coast - Complete Mage, p.45

this feat doesn't give school choice

**Comment by BahamutDragon** [comment]
It gives me a choice.

![image](https://cloud.githubusercontent.com/assets/4307487/20869290/0536c600-ba24-11e6-8b7d-4a8009722636.png)

**Comment by nevarim** [comment]
under choices you haven't any school choosed

**Comment by BahamutDragon** [comment]
Mate, 

Look again, and you will see the choice is 'Abjuration'. The duplicate Spell Focus under the Metamagic School Focus is the choice.

I think the reason will become clear if you read the full text:  
Benefit: Choose a school of magic for which you have the Spell Focus feat, or the school in which you have specialized. Three times per day, you can reduce by one level the cost of a metamagic feat applied to a spell of the chosen school. If you prepare spells, you can have only up to three such reduced cost spells prepared at any time.

In my example, the school is based off of the Spell Focus choice. Instead of using a specialty. Let me show you another screen shot:

![image](https://cloud.githubusercontent.com/assets/4307487/20911671/7b943d78-bb1e-11e6-9624-3fe4b4bc7518.png)

I think you will again say I failed to make a choice, but this is a matter of perception. For if you look at the character sheet, the choice is very apparent. This shows you that the UI is not the final say on when a choice has been made. Only when a choice has been made by a user.

![image](https://cloud.githubusercontent.com/assets/4307487/20911701/b0af0696-bb1e-11e6-95ba-8aeb9b7571b4.png)

The lesson to understand, complicated functions of a feat are handled behind the scenes, but the final result is usually correct. The feat takes choices from two different sources, not a school choice. It chooses either from Spell Focus, or the Wizard Specialist choice. In which case, the choice is made for you.

This works as intended. When in doubt verify whether the final result is accurate. If the result is accurate, then nothing needs to be addressed. 

Best,
