### ISSUE TITLE
D&D 3.5 god and weapon

### ISSUE THREAD

**Issue by nevarim** [BahamutDragon/pcgen#616]
hi 

when you choose a deity you can use the weapon of that deity, i choose moradin

Moradin Description:    Pantheon: Base,PH,FavoredWeaponWarhammer   Pantheon: Base,FavoredWeaponWarhammer,PH   Dominii: Earth, Good, Law, Protection   Arma preferita   Source: Wizards of the Coast - Player's Handbook, p.107

but i canno use warhammer unless i take feat for it

is it right?

**Comment by BahamutDragon** [comment]
Class Features
All of the following are class features of the cleric.
Weapon and Armor Proficiency: Clerics are
proficient with all simple weapons, with all types of
armor (light, medium, and heavy), and
with shields (except tower
shields).
Every deity has a favored
weapon (see Deities, page 106),
and his or her clerics consider it
a point of pride to wield that
weapon. A cleric who chooses
the War domain receives the
Weapon Focus feat related to that
weapon as a bonus feat. He also
receives the appropriate Martial
Weapon Proficiency feat as a bonus
feat, if the weapon falls into that
category. See Chapter 5: Feats for
details.

**Comment by FerretDave** [comment]
Greetings,I have always read that as being they are proficient in the weapon, and if they choose war domain they also get the focus feat for it... however that may be wrong...                                                                                                                                                                                                                                                                                                                                        CheersDave     oxxxxxxx{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;>                                                                                                                                                                                                                From: BahamutSent: Thursday, 29 December 2016 01:57To: BahamutDragon/pcgenReply To: BahamutDragon/pcgenCc: SubscribedSubject: Re: [BahamutDragon/pcgen] D&D 3.5 god and weapon (#616)Class Features
All of the following are class features of the cleric.
Weapon and Armor Proficiency: Clerics are
proficient with all simple weapons, with all types of
armor (light, medium, and heavy), and
with shields (except tower
shields).
Every deity has a favored
weapon (see Deities, page 106),
and his or her clerics consider it
a point of pride to wield that
weapon. A cleric who chooses
the War domain receives the
Weapon Focus feat related to that
weapon as a bonus feat. He also
receives the appropriate Martial
Weapon Proficiency feat as a bonus
feat, if the weapon falls into that
category. See Chapter 5: Feats for
details.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BahamutDragon/pcgen","title":"BahamutDragon/pcgen","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BahamutDragon/pcgen"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BahamutDragon in #616: Class Features\r\nAll of the following are class features of the cleric.\r\nWeapon and Armor Proficiency: Clerics are\r\nproficient with all simple weapons, with all types of\r\narmor (light, medium, and heavy), and\r\nwith shields (except tower\r\nshields).\r\nEvery deity has a favored\r\nweapon (see Deities, page 106),\r\nand his or her clerics consider it\r\na point of pride to wield that\r\nweapon. A cleric who chooses\r\nthe War domain receives the\r\nWeapon Focus feat related to that\r\nweapon as a bonus feat. He also\r\nreceives the appropriate Martial\r\nWeapon Proficiency feat as a bonus\r\nfeat, if the weapon falls into that\r\ncategory. See Chapter 5: Feats for\r\ndetails."}],"action":{"name":"View Issue","url":"https://github.com/BahamutDragon/pcgen/issues/616#issuecomment-269570552"}}}

**Comment by nevarim** [comment]
hi

i'm agree, but i don't know if is possiblee to limit weapon proficiencies to a single weapon (for example for oghma only for long sword)

**Comment by BahamutDragon** [comment]
Mates,

There is nothing official here for me to act upon. You may house rule clerics are granted proficiencies if you would like (I have provided the samples required to replicate the desired effect in my specific replies below), but that is not how the class feature reads, and I will not change core features based upon loose interpretations of the rules. D&D 3.5 has been around for 13 years and I have not seen anything to indicate clerics are granted additional proficiencies based upon deity selection. Had that been the case, the first line would have stated that - Simple, and proficient with the deities favored weapon. Or there would be errata to that effect. Find errata or an updated rule and the feature will be updated accordingly.

If you need further proof that your interpretation is flawed, then look at the War Domain write up:

> WAR DOMAIN
> Deities: Corellon Larethian, Erythnul, Gruumsh, Heironeous, Hextor.
> Granted Power: Free Martial Weapon Proficiency with deity’s favored weapon (if necessary) and Weapon Focus with the deity’s favored weapon.
> The favored weapons of the war deities are as follows; Corellon, longsword; Erythnul, morningstar; Gruumsh, spear (or longspear); Heironeous, longsword; Hextor, flail (light or heavy).

@FerretDave That would be a house ruling, not following the rules as written. The stated weapon proficiencies of the cleric class is simple, nothing else. It mentions clerics use the favored weapon as a point of pride, but no proficiency is granted. The exception to this statement comes after with the mention of the War Domain - Which grants both Weapon Focus for the Weapon, as well as Martial Weapon Proficiency, should the weapon be classified as a martial weapon. This is unlike Pathfinder, which explicitly grants a proficiency with the deity favored weapon. Though Pathfinder also grants the exotic proficiency, Bastard Swords and Spike Chains. The difference is not a huge game changer.

@nevarim Granting a single proficiency is quite easy. You can just house rule the proficiency, and follow the Pathfinder example (AUTO:WEAPONPROF|DEITYWEAPONS), or you can grant Martial Weapon Proficiency which would grant a choice of one Martial Weapon. (BONUS:ABILITYPOOL|Martial Weapon Proficiency|1)

I hope this has cleared up the official rules. I am closing this issue as there is nothing for me to act upon.

Best,

**Comment by FerretDave** [comment]
‎I guess we've been playing it wrong all these years :-)No worries.‎ There's so many rules so we skim read a lot and easily miss minor bits like this. To be honest there's many times that we use rules from 3.0 or even 2nd edition as we haven't realised they have been rewritten or errata'd!                                                                                                                                                                                                                                                                                                                                        CheersDave     oxxxxxxx{;;;;;;;;;;;;;;;;;;;;;;;;;;;;;>                                                                                                                                                                                                                From: BahamutSent: Saturday, 31 December 2016 03:32To: BahamutDragon/pcgenReply To: BahamutDragon/pcgenCc: Dave; MentionSubject: Re: [BahamutDragon/pcgen] D&D 3.5 god and weapon (#616)Mates,
There is nothing official here for me to act upon. You may house rule clerics are granted proficiencies if you would like (I have provided the samples required to replicate the desired effect in my specific replies below), but that is not how the class feature reads, and I will not change core features based upon loose interpretations of the rules. D&D 3.5 has been around for 13 years and I have not seen anything to indicate clerics are granted additional proficiencies based upon deity selection. Had that been the case, the first line would have stated that - Simple, and proficient with the deities favored weapon. Or there would be errata to that effect. Find errata or an updated rule and the feature will be updated accordingly.
If you need further proof that your interpretation is flawed, then look at the War Domain write up:

WAR DOMAIN
Deities: Corellon Larethian, Erythnul, Gruumsh, Heironeous, Hextor.
Granted Power: Free Martial Weapon Proficiency with deity’s favored weapon (if necessary) and Weapon Focus with the deity’s favored weapon.
The favored weapons of the war deities are as follows; Corellon, longsword; Erythnul, morningstar; Gruumsh, spear (or longspear); Heironeous, longsword; Hextor, flail (light or heavy).

@FerretDave That would be a house ruling, not following the rules as written. The stated weapon proficiencies of the cleric class is simple, nothing else. It mentions clerics use the favored weapon as a point of pride, but no proficiency is granted. The exception to this statement comes after with the mention of the War Domain - Which grants both Weapon Focus for the Weapon, as well as Martial Weapon Proficiency, should the weapon be classified as a martial weapon. This is unlike Pathfinder, which explicitly grants a proficiency with the deity favored weapon. Though Pathfinder also grants the exotic proficiency, Bastard Swords and Spike Chains. The difference is not a huge game changer.
@nevarim Granting a single proficiency is quite easy. You can just house rule the proficiency, and follow the Pathfinder example (AUTO:WEAPONPROF|DEITYWEAPONS), or you can grant Martial Weapon Proficiency which would grant a choice of one Martial Weapon. (BONUS:ABILITYPOOL|Martial Weapon Proficiency|1)
I hope this has cleared up the official rules. I am closing this issue as there is nothing for me to act upon.
Best,

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/BahamutDragon/pcgen","title":"BahamutDragon/pcgen","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/BahamutDragon/pcgen"}},"updates":{"snippets":[{"icon":"PERSON","message":"@BahamutDragon in #616: Mates,\r\n\r\nThere is nothing official here for me to act upon. You may house rule clerics are granted proficiencies if you would like (I have provided the samples required to replicate the desired effect in my specific replies below), but that is not how the class feature reads, and I will not change core features based upon loose interpretations of the rules. D\u0026D 3.5 has been around for 13 years and I have not seen anything to indicate clerics are granted additional proficiencies based upon deity selection. Had that been the case, the first line would have stated that - Simple, and proficient with the deities favored weapon. Or there would be errata to that effect. Find errata or an updated rule and the feature will be updated accordingly.\r\n\r\nIf you need further proof that your interpretation is flawed, then look at the War Domain write up:\r\n\r\n\u003e WAR DOMAIN\r\n\u003e Deities: Corellon Larethian, Erythnul, Gruumsh, Heironeous, Hextor.\r\n\u003e Granted Power: Free Martial Weapon Proficiency with deity’s favored weapon (if necessary) and Weapon Focus with the deity’s favored weapon.\r\n\u003e The favored weapons of the war deities are as follows; Corellon, longsword; Erythnul, morningstar; Gruumsh, spear (or longspear); Heironeous, longsword; Hextor, flail (light or heavy).\r\n\r\n@FerretDave That would be a house ruling, not following the rules as written. The stated weapon proficiencies of the cleric class is simple, nothing else. It mentions clerics use the favored weapon as a point of pride, but no proficiency is granted. The exception to this statement comes after with the mention of the War Domain - Which grants both Weapon Focus for the Weapon, as well as Martial Weapon Proficiency, should the weapon be classified as a martial weapon. This is unlike Pathfinder, which explicitly grants a proficiency with the deity favored weapon. Though Pathfinder also grants the exotic proficiency, Bastard Swords and Spike Chains. The difference is not a huge game changer.\r\n\r\n@nevarim Granting a single proficiency is quite easy. You can just house rule the proficiency, and follow the Pathfinder example (AUTO:WEAPONPROF|DEITYWEAPONS), or you can grant Martial Weapon Proficiency which would grant a choice of one Martial Weapon. (BONUS:ABILITYPOOL|Martial Weapon Proficiency|1)\r\n\r\nI hope this has cleared up the official rules. I am closing this issue as there is nothing for me to act upon.\r\n\r\nBest, "}],"action":{"name":"View Issue","url":"https://github.com/BahamutDragon/pcgen/issues/616#issuecomment-269846889"}}}
