### ISSUE TITLE
Magic of Incarnum wonk(?)

### ISSUE THREAD

**Issue by AriMatt2** [BahamutDragon/pcgen#700]
I want to preface this by saying that I'm not sure what Complete (works) means in terms of building stuff, but a few things in Magic of Incarnum don't seem to work right. Azurin don't get their extra level 1 feat, for instance.

The classes have Soulmeld pop up under the Class Features tab strangely. Totemest, for instance, gets Totemest Soulmeld to pop up at class level 4, corresponding to nothing, and nothing in it is qualifiable. It is also not under the dropdown for Totemest Class Features. The same applies for the Soulborn. Incarnates have it happen at level 1 in the class.

If this is known then to not waste the post entirely, I can't find Psychic Rogue from the Mind's Eye as a class.

**Comment by BahamutDragon** [comment]
Mate,

My definition of Complete (Works) is just saying the entire book's contents are included and you can load the content and most everything should do something. It does not mean everything has been tested and works perfectly, nor does it mean every variable or utmost detail has been incorporated. In most cases I have made the foundation classes, and they display all of their features at the correct levels. 

This is a side hobby for me. I do not have the time to focus on making every book complete to perfection. Which is why I host these home creations on here. I made most of these for my own gaming group, and the focus was what they needed for our adventures. Others are encouraged to complete items their group needs, and share those items with the public. Some people request books, and I will create the shell and basic functionality. Again, this is a community project, with the hope that people will use these and improve them. 

I review the improvements certainly, and make sure these books maintain the publisher standards as best as I can. 

Now, on to the main thrust of the post, You report that Magic of Incarnum appears to have some incorrect coding, and I can certainly investigate and correct that, same with the Mind's Eye. 

Just so you know, best practice when reporting issues is to make one report per issue. This allows the community to participate and focus on one issue.

Best,

**Comment by BahamutDragon** [comment]
#705 is the Minds Eye request.

**Comment by BahamutDragon** [comment]
Magic of Incarnum should be fixed. I only tested with a 5th level totemist.  Double check and make sure it is all correctly working now.

**Comment by AriMatt2** [comment]
Trip Report: Got good news and bad news.

The good news is that I think I figured out the cause of the problems. The bad news is that there's other problems and I don't think fixing things will be easy or at least non-tedious.

But here we go.

It looks like the program is confusing being able to bind a soulmeld to a chakra and being able to shape it to that chakra. To be able to bind to that chakra you need the right level or feat, and either are wearing nothing in the slots corresponding to the chakra the meld is being bound to or nothing magical in those slot or slots. That second one is unfortunately really fiddly.

It also doesn't respect the maximum number of chakra binds, but that's a bit less meaningful at the moment, especially as there are ways around the max in the book.  It also seems to be calculating how many can be shaped wrongly. It uses the right base, but seems to be giving a bonus or penalty based on the attribute instead of using the lesser of (Con-10) or the number for your class, plus any extra from feats. The bonus is limited to two for Incarnate and one for Soulborn, if that helps. Totemist seems to be completely using Chakra Binds for soulmeld selections, at least if the extra one at level 11 comes from where I think it is. Also, totem chakra is never made available.

I hope this helps, and can do more looking if you want. (Using most recent download from here and most recent autobuild [6.07.02-DEV] from PCGen.)
