### ISSUE TITLE
Energy Admixture Feat 35e

### ISSUE THREAD

**Issue by Thorngage** [BahamutDragon/pcgen#873]
When trying to add the Energy admixture Feat to my Cloistered Cleric NPC i got this message 

![error duruk val](https://user-images.githubusercontent.com/46561511/51110219-2b761d00-17f8-11e9-901d-9d39d5ddb7e7.JPG)

I will put the log here in a txt

[Error Duruk Val.txt](https://github.com/BahamutDragon/pcgen/files/2754946/Error.Duruk.Val.txt)

**Comment by BahamutDragon** [comment]
You had NPEs before you made the Monk. The log is missing the beginning to help determine if this is an issue on my end or you need to raise the issue with the pcgen volunteers. 

I altered the feat in how it should work. The root cause of the NPEs does need to be addressed. Any NPE will result in an unstable program.

If you are able to reproduce the issue let me know the steps or supply the character file.

Best,
