### ISSUE TITLE
Adjustments and descriptions

### ISSUE THREAD

**Issue by v13jf9** [BahamutDragon/pcgen#901]
I was hoping for assistance on how to add/insert the language (Undercommon) to the Dark Elf  sub race in PH, and adding descriptions to the wizard Lvl 0 cantrips ie Toll the Dead, True Strike, etc.

thanks for any assistance that can be provided

**Comment by BahamutDragon** [comment]
Mate,

Adding things just requires a decent text editor and patience. 

I can add the description to the cantrip ability you take since the spell that is displayed on the character sheet has the description.

Is there any official citation about granting undercommon to the Dark Elf?

**Comment by v13jf9** [comment]
ah i see i didnt notice that they do appear in the character sheet, i was more referencing when picking the cantrips the desc. was missing.  as for the language this is the only place thats official DnD material that mentions PC drow elfs knowing undercommon. 
[Drow Rogue 1.pdf](https://github.com/BahamutDragon/pcgen/files/3113093/Drow.Rogue.1.pdf)
![Screenshot_20190424-104415_Samsung Internet](https://user-images.githubusercontent.com/7107774/56673795-9304f980-667e-11e9-8249-aa80f9bad97e.jpg)

**Comment by BahamutDragon** [comment]
Mate, Drow automatically knowing Undercommon (A trade language for the underdark realm) is not a given. Mike Mearls says it was intentional not to grant it as a base language:

https://www.sageadvice.eu/2016/07/24/drow-pcs-dont-speak-undercommon-automatically-oversight-or-intentional/

![image](https://user-images.githubusercontent.com/4307487/56701804-b4cda300-66b5-11e9-86b8-fef09a99407b.png)

**Comment by v13jf9** [comment]
interesting, ill have to delve deeper to truly understand why WotC would add that to theyre own pregenerated characters.

and do you have any info about the documentation for PCGen so i can "code" addition homebrew and output sheets?

thanks for all your help so far
