### ISSUE TITLE
3.5E: Magic of Faerun + Spell Compendium - Scintillating Sphere

### ISSUE THREAD

**Issue by dmcbride** [BahamutDragon/pcgen#938]
If I have both MoF and SC loaded, then Scintillating Sphere still says Halruaa only, even though the one in SC doesn't have any regional limitation.

**Comment by BahamutDragon** [comment]
Mate, I daresay that means every time you load your sourcebooks, that you allow PCGen to randomly select the winner. You need to set the preference in PCGen to use the latest sourcebook. MoF was released in 2001, while SC was released in 2005. SC wins by being the latest. 

![image](https://user-images.githubusercontent.com/4307487/68998535-3d857980-0868-11ea-8095-e6499a3aff6a.png)

**Comment by dmcbride** [comment]
That checkbox is already selected, I think that's a default on a fresh install as I never went into this config setting before now.  So if you can't reproduce this, then I must be doing something else wrong. Thanks, though.

**Comment by BahamutDragon** [comment]
If that is not working, then the PCGen team needs to address it. All I can do is edit older sourcebook files, which I would rather not do since that causes confusion.

**Comment by Llisandur** [comment]
This appears to be a problem with the priority of the RANK tag in the .pcc file. The solution that the PCGen team is going to use is to replace the single-digit RANK tag with the same info as the SOURCEDATE tag, without the hyphen.

You can use the regex replace below to do this quickly.

Find: SOURCEDATE:([0-9]{4})-([0-9]{2})
Replace: SOURCEDATE:$1-$2\nRANK:$1$2

Find: \nRANK:[0-9]$
Replace: <nothing/delete>

As a note, this will put the RANK tag in the .pcc below the SOURCEDATE tag. It otherwise won't affect the loading of the sources, except that they should overwrite by the source date now.

**Comment by BahamutDragon** [comment]
Fix implemented.
