### ISSUE TITLE
Echo Knight - Fighter Subclass request (5e)

### ISSUE THREAD

**Issue by Proxxy0** [BahamutDragon/pcgen#992]
Would it be possible to add in the new Echo Knight subclass from Explorer's Guide to Wildemount? The new campaign I just started has a player who want's to play that archetype, and I was hoping I wouldn't have to stray from using PCGen to keep track of the characters. Thanks a billion for all the work put into this project!

**Comment by BahamutDragon** [comment]
I need a PDF if possible. I am not familiar with that source.

**Comment by AdoniMaster** [comment]
Is there a way to create a spellbook for a clerics that is just the learned spells for the day?  I know I get the whole list of spells that I use and mark, but it would be great if I could have a subset as a spellbook.


John Kockler
Owner at Adoni Networks
A  647 N 22nd Street La Crosse, WI 54601
P  608-785-3030 ext. 2000  <tel:608-785-3030%20ext.%20200> M  608-385-3183<tel:608-385-3183>
E  jkockler@adoninetworks.com  <mailto:jkockler@adoninetworks.com> W www.adoninetworks.com <http://www.adoninetworks.com/>
Please submit any service requests to support@adoninetworks.com<mailto:support@adoninetworks.com>.  If your issue is urgent, please phone (608) 785-3030 and inform the dispatcher.

**Comment by FerretDave** [comment]
That's a question for the pcgen team, not Bahamut, but unfortunately the
answer is no

**Comment by Proxxy0** [comment]
I couldn't seem to find a pdf for the subclass, probably due to how recent the new book is, but there is a Wikidot page for the class that contains its information [here](http://dnd5ed.wikidot.com/fighter:echo-knight). If I can manage to scrape together some funds to grab the new book myself, I could try to get some pdfs made, if necessary.

**Comment by BahamutDragon** [comment]
Added to 6.08. Let me know if you need Master as well. Currently working through a few requests.

**Comment by Proxxy0** [comment]
Thanks, 6.08 is perfect! You do such an awesome job with all of this!
